version: '3.7'

services:
  db:
    image: de.erik.lab/docker-db-lab
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -d ${DATABASE_NAME} -U ${DATABASE_USERNAME}
      interval: 5s

  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/mydatabase
      DATABASE_USERNAME: myuser
      DATABASE_PASSWORD: mypass